# .rubocop.yml
require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 6.1.6.1
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - '*.lock'
    - '.rubocop.yml'
    - 'test/ui_test_suite.rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 19

Style/Documentation:
  Exclude:
    - 'test/**/*'

Style/NumericPredicate:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
