language: ruby
rvm:
  - 2.6.5
install:
  - gem install travis
branches:
  only:
    - master
    - development
    - burp
services:
  - docker
env:
  - BURP_ENABLE=y
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - sudo apt-get update && sudo apt-get -y install curl unzip jq
  - sudo curl -O https://releases.hashicorp.com/vault/1.0.1/vault_1.0.1_linux_amd64.zip
  - sudo unzip vault_1.0.1_linux_amd64.zip
  - sudo mv vault /usr/local/bin
  - bin/burp_start.sh "${BURP_DOCKER_IMAGE}" "${BURP_DOCKER_KEY}"
script:
<<<<<<< HEAD
  - bin/load_env_secrets.sh -p secret/kdux/scp/staging-new/scp_config.json -s secret/kdux/scp/staging-new/scp_service_account.json -e test -n single-cell-portal-staging

=======
  - bin/load_env_secrets.sh -p secret/kdux/scp/staging/scp_config.json -s secret/kdux/scp/staging/scp_service_account.json -r secret/kdux/scp/staging/read_only_service_account.json -e test -n single-cell-portal-staging
>>>>>>> master
after_success:
  - bin/burp_scan.sh "${BURP_DOCKER_IMAGE}"
