language: ruby
dist: bionic
rvm:
  - 2.6.6
install:
  - gem install travis
branches:
  only:
    - master
    - development
services:
  - docker
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - sudo apt-get update && sudo apt-get -y install curl unzip jq
  - sudo curl -O https://releases.hashicorp.com/vault/1.0.1/vault_1.0.1_linux_amd64.zip
  - sudo unzip vault_1.0.1_linux_amd64.zip
  - sudo mv vault /usr/local/bin
  - |
    export BURP_ENABLE=$(
      [[ "${TRAVIS_COMMIT_MESSAGE}" = *"[burp-scan]"* ]] ||
      [[ "${TRAVIS_PULL_REQUEST}"   = "false" ]] ;
      echo $?
    )
    export BURP_ENABLE=-1
    if [ "${BURP_ENABLE}" = "0" ]; then
      bin/burp_start.sh "${BURP_DOCKER_IMAGE}" "${BURP_SA_KEY}"
      export BURP_PROXY="http://$(hostname):8080"
    fi
script:
  - bin/load_env_secrets.sh -p secret/kdux/scp/staging/scp_config.json -s secret/kdux/scp/staging/scp_service_account.json -r secret/kdux/scp/staging/read_only_service_account.json -e test -n single-cell-portal-test
after_success:
  - |
    export BURP_ENABLE=-1
    if [ "${BURP_ENABLE}" = "0" ]; then
      bin/burp_scan.sh "${BURP_DOCKER_IMAGE}" "${BURP_SA_KEY}" "${BURP_BUCKET}" "${TRAVIS_REPO_SLUG}"
    fi
