name: 'Pull gcloud container and activate service account'
description: 'Pulls gcloud Docker image and activates the requested service account to use in calling gcloud'
inputs:
  service_account_vault_path:
    description: 'Path to service account in vault'
    required: true
  gcloud_docker_image:
    description: 'gcloud Docker image name/vesion tag'
    required: false
    default: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  container_name:
    description: 'name of container to create and access volumes from'
    required: false
    default: 'gcloud-config'

runs:
  using: 'composite'
  steps:
    - name: Install vault
      uses: ./.github/actions/install-vault-and-utils
    - name: Download gcloud Docker image
      shell: bash
      run: |
        docker pull ${{ inputs.gcloud_docker_image }}
    - name: Authenticate to gcloud and docker
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        SERVICE_ACCOUNT_PATH: '/tmp/scp_service_account.json'
      shell: bash
      run: |
        # this will create a Docker volume called 'gcloud-config' that contains credentials for use with gcloud
        export VAULT_TOKEN=$( vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID )
        vault read -format=json $${ inputs.service_account_vault_path }} | jq .data > $SERVICE_ACCOUNT_PATH
        docker run -v "$SERVICE_ACCOUNT_PATH:$SERVICE_ACCOUNT_PATH" --name ${{ inputs.container_name }} \ 
               ${{ inputs.gcloud_docker_image }} gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT_PATH
