name: Build and publish single-cell-portal Docker image
on:
  push:
    branches:
      - jb-github-actions-cd
      - development
      - master
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: 'gcr.io/broad-singlecellportal-staging/single-cell-portal'
  GCLOUD_DOCKER_IMAGE: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  VAULT_SECRET_PATH: 'secret/kdux/scp/staging/scp_service_account.json'
  CONTAINER_NAME: 'gcloud-config'

jobs:
  Build-And-Publish-Docker-Image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure gcloud container and activate service account
        uses: ./.github/actions/configure-gcloud-container
        with:
          gcloud_docker_image: ${{ env.GCLOUD_DOCKER_IMAGE }}
          container_name: ${{ env.CONTAINER_NAME }}
          vault_secret_path: ${{ env.VAULT_SECRET_PATH }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Authenticate to docker
        shell: bash
        run: |
          # auth into GCR via Docker with token from service account
          AUTH_TOKEN=$(docker run --rm --volumes-from ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE_NAME }} gcloud auth print-access-token)
          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://gcr.io
      - name: Build requested Docker image
        run: |
          # substitute 'docker run ARGS gcloud' for regular gcloud command and determine if VERSION_TAG should be set
          if [[ ${{ github.ref_name }} == 'master' ]]; then
            bin/build_image.sh -g "docker run --rm --volumes-from gcloud-config $GCLOUD_DOCKER_IMAGE gcloud"
          else
            bin/build_image.sh -v ${{ github.ref_name }} -g "docker run --rm --volumes-from gcloud-config $GCLOUD_DOCKER_IMAGE gcloud"
          fi
          
          
