name: Build and publish single-cell-portal Docker image
on:
  push:
    branches:
      - development
  release:
    types: [published]
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: 'gcr.io/broad-singlecellportal-staging/single-cell-portal'
  VAULT_SECRET_PATH: 'secret/kdux/scp/staging/scp_service_account.json'

jobs:
  Build-And-Publish-Docker-Image:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure gcloud
        uses: ./.github/actions/setup-gcloud
        with:
          service_account_email: '839419950053-compute@developer.gserviceaccount.com'
          google_cloud_project: 'broad-singlecellportal-staging'
      - name: Build requested Docker image
        run: |
          # determine if VERSION_TAG should be set
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            bin/build_image.sh
          else
            bin/build_image.sh -v ${{ github.ref_name }}
          fi
          
          
