name: Deploy to production SCP instance
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: 'gcr.io/broad-singlecellportal-staging/single-cell-portal'
  GCLOUD_DOCKER_IMAGE: "gcr.io/google.com/cloudsdktool/google-cloud-cli:latest"
  IMAGE_NAME: 'prod-gcloud-config'
  PORTAL_SECRETS_PATH: 'secret/kdux/scp/production/scp_config.json'
  MAIN_SERVICE_ACCOUNT: 'secret/kdux/scp/production/scp_service_account.json'
  READ_ONLY_SERVICE_ACCOUNT: 'secret/kdux/scp/production/read_only_service_account.json'
  GOOGLE_PROJECT: 'broad-singlecellportal'
  COMPUTE_ZONE: 'us-central1-a'
  REMOTE_HOST: 'singlecell-01'

jobs:
  Deploy-To-Staging:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install vault and other utilities
        uses: ./.github/actions/install-vault-and-utils
      - name: Configure gcloud container and activate service account
        uses: ./.github/actions/configure-gcloud-container
        with:
          gcloud_docker_image: ${{ env.GCLOUD_DOCKER_IMAGE }}
          image_name: ${{ env.IMAGE_NAME }}
          vault_secret_path:  ${{ env.MAIN_SERVICE_ACCOUNT }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Extract secrets to env file
        uses: ./.github/actions/extract-vault-secret-to-file
        with:
          vault_secret_path: ${{ env.PORTAL_SECRETS_PATH }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
          output_filename: 'scp_config.env'
          output_format: 'env'
      - name: Extract main service account json
        uses: ./.github/actions/extract-vault-secret-to-file
        with:
          vault_secret_path: ${{ env.MAIN_SERVICE_ACCOUNT }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
          output_filename: 'scp_service_account.json'
          output_format: 'json'
      - name: Extract readonly service account json
        uses: ./.github/actions/extract-vault-secret-to-file
        with:
          vault_secret_path: ${{ env.READ_ONLY_SERVICE_ACCOUNT }}
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
          output_filename: 'read_only_service_account.json'
          output_format: 'json'
      - name: Run deploy script
        shell: bash
        run: |
          bin/deploy-github.sh -b master -e production -g $GOOGLE_PROJECT -G $IMAGE_NAME -h $REMOTE_HOST \
                               -p $PORTAL_SECRETS_PATH -s $MAIN_SERVICE_ACCOUNT -r $READ_ONLY_SERVICE_ACCOUNT
