name: SCP Continuous Integration
on:
  push:
    branches:
      - development
      - master
  pull_request:
env:
  DOCKER_IMAGE_NAME: "gcr.io/broad-singlecellportal-staging/single-cell-portal"
  GOOGLE_CLOUD_PROJECT: 'broad-singlecellportal-staging'

jobs:
  Run-All-Tests:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure gcloud
        uses: ./.github/actions/setup-gcloud
      - name: Build image and setup env
        id: build-image-setup-env
        uses: ./.github/actions/docker-build-env-setup
      - name: Load secrets and run tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          RAILS_LOG_TO_STDOUT: true
          DOCKER_IMAGE_TAG: ${{ steps.build-image-setup-env.outputs.docker-tag }}
          SCP_CONFIG: 'scp-config-json'
          DEFAULT_SA: 'default-sa-keyfile'
          READONLY_SA: 'read-only-sa-keyfile'
          CI: true
        run: |
          bin/load_env_secrets.sh -p $SCP_CONFIG -s $DEFAULT_SA -r $READONLY_SA -g $GOOGLE_CLOUD_PROJECT -e test \
                                  -v $DOCKER_IMAGE_TAG -n single-cell-portal-test
      - name: Preserve all test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-logs
          path: |
            log/test.log
            log/delayed_job.test.log
