name: Terra Orchestration API Smoke Test
on:
  schedule:
    - cron: "0 8 * * 1,3,5"
env:
  DOCKER_IMAGE_NAME: "gcr.io/broad-singlecellportal-staging/single-cell-portal"

jobs:
  Run-Orch-Smoketest:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build image and setup env
        uses: ./.github/actions/docker-build-env-setup
      - name: Load secrets and run tests
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
          ORCH_SMOKE_TEST: true
          CI: true
        run: |
          export VAULT_TOKEN=$( vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID )
          bin/load_env_secrets.sh -p secret/kdux/scp/staging/scp_config.json \
                                  -s secret/kdux/scp/staging/scp_service_account.json \
                                  -e test -v $DOCKER_IMAGE_TAG -n single-cell-portal-test \
                                  -c bin/run_orch_smoke_test.sh
      - name: Preserve all test logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            log/test.log
